### ISSUE TITLE
Suggestion: improve customisation 

### ISSUE THREAD

**Issue by raysdigitalfootprint** [Godofdrakes/barrows-potential#2] opened 2023-06-10 20:45 UTC
Unsure the best way to do it but I'd like a QOF for highlighting crypt NPCS for 86.36% eg 2 skeletons and 1 bloodworm with all brothers complete.

**Comment by Godofdrakes** [comment] 2023-07-26 00:29
Dupe of https://github.com/Godofdrakes/barrows-potential/issues/1

**Closed as not planned by Godofdrakes** 2023-07-26 00:29 UTC
Labels: duplicate
